// muDock's XScore test
//
// Compares the four implemented terms (VDW, HB, HP, RT) and the predicted affinity (PKD) against 
// values produced by XScore v1.3, stored into <name>_xscore.ref. 
//
// References are generated by script/gen_xscore_reference.sh.
//
// Exit codes:  0 = pass, 1 = mismatch, MUDOCK_CTEST_SKIP_RETURN_CODE = reference not available.

#include <boost/program_options.hpp>
#include <cctype>
#include <cmath>
#include <command_line_args.hpp>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <memory>
#include <mudock/compute/manager.hpp>
#include <mudock/compute/pipeline.hpp>
#include <mudock/format/reader.hpp>
#include <mudock/knobs.hpp>
#include <mudock/log.hpp>
#include <mudock/mudock.hpp>
#include <mudock/type_alias.hpp>
#include <mudock/utils.hpp>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#ifndef MUDOCK_CTEST_SKIP_RETURN_CODE
  #define MUDOCK_CTEST_SKIP_RETURN_CODE 77
#endif

namespace {

  constexpr std::array<std::string_view, 5> term_names{"VDW", "HB", "HP", "RT", "PKD"};

  constexpr mudock::fp_type abs_tol = mudock::fp_type{1e-4f};
  constexpr mudock::fp_type rel_tol = mudock::fp_type{1e-4f};

  [[nodiscard]] mudock::fp_type tolerance_for(const mudock::fp_type reference) {
    return abs_tol + rel_tol * std::fabs(reference);
  }

  [[nodiscard]] std::optional<mudock::fp_type> reference_value(const std::string& text,
                                                               const std::string_view term) {
    const std::string key = "XSCORE_" + std::string{term};
    std::stringstream stream{text};
    std::string line;
    while (std::getline(stream, line)) {
      const auto first = line.find_first_not_of(" \t\r");
      if (first == std::string::npos || line[first] == '#')
        continue;
      std::stringstream line_stream{line};
      std::string parsed_key;
      mudock::fp_type value{0};
      if (line_stream >> parsed_key >> value && parsed_key == key)
        return value;
    }
    return std::nullopt;
  }

  [[nodiscard]] std::optional<mudock::fp_type> scored_value(const std::string& score,
                                                            const std::string_view term) {
    const std::string key = std::string{term} + "=";
    for (auto pos = score.find(key); pos != std::string::npos; pos = score.find(key, pos + 1)) {
      if (pos != 0 && (std::isspace(static_cast<unsigned char>(score[pos - 1])) == 0))
        continue;
      std::stringstream stream{score.substr(pos + key.size())};
      mudock::fp_type value{0};
      if (stream >> value)
        return value;
      return std::nullopt;
    }
    return std::nullopt;
  }

} // namespace

int main(int argc, char* argv[]) {
  namespace po                       = boost::program_options;
  std::filesystem::path protein_path = std::filesystem::path{"protein.pdb"};
  std::filesystem::path ligand_path  = std::filesystem::path{"ligand.mol2"};
  std::filesystem::path ref_path     = std::filesystem::path{"reference.ref"};

  po::options_description arguments_description("Available options");
  arguments_description.add_options()("help", "print this help message");
  arguments_description.add_options()("protein,p",
                                      po::value(&protein_path)->default_value(protein_path),
                                      "Path to the protein file");
  arguments_description.add_options()("ligand,l",
                                      po::value(&ligand_path)->default_value(ligand_path),
                                      "Path to the ligand file");
  arguments_description.add_options()("ref,r",
                                      po::value(&ref_path)->default_value(ref_path),
                                      "Path to the frozen XScore reference file");

  po::options_description all("Allowed Options");
  all.add(arguments_description);
  po::variables_map vm;
  po::store(po::command_line_parser(argc, argv).options(all).run(), vm);
  po::notify(vm);

  if (vm.count("help") > 0) {
    std::stringstream help;
    help << all;
    mudock::info(help.str());
    return EXIT_SUCCESS;
  }

  if (!std::filesystem::exists(ref_path)) {
    mudock::info("No XScore reference at ", ref_path.string(), ", skipping.");
    return MUDOCK_CTEST_SKIP_RETURN_CODE;
  }
  if (!std::filesystem::exists(protein_path) || !std::filesystem::exists(ligand_path)) {
    mudock::info("Missing protein or ligand for ", ref_path.string(), ", skipping.");
    return MUDOCK_CTEST_SKIP_RETURN_CODE;
  }

  const auto reference_text = read_from_stream(std::ifstream(ref_path));

  mudock::info("Reading and parsing protein ", protein_path.string(), " ...");
  auto protein =
      std::make_shared<mudock::dynamic_molecule>(mudock::parser<mudock::dynamic_molecule>(protein_path));

  mudock::info("Reading and parsing ligand ", ligand_path.string(), " ...");
  auto ligand =
      std::make_shared<mudock::static_molecule>(mudock::parser<mudock::static_molecule>(ligand_path));

  mudock::info("Scoring with the X-Score pipeline ...");
  mudock::x_score_pipeline pipe{protein};

  auto input_queue  = std::make_shared<mudock::safe_queue<mudock::static_molecule>>();
  auto output_queue = std::make_shared<mudock::safe_queue<mudock::static_molecule>>();
  input_queue->initialize(1);
  output_queue->initialize(1);

  auto ligand_in = std::make_unique<mudock::static_molecule>(*ligand);
  input_queue->enqueue(ligand_in);
  input_queue->send_terminate_signal();
  {
    const auto knobs = mudock::knobs{1, 1, 0, 0, 123};
    auto threadpool  = mudock::threadpool();
    mudock::manager({std::string{use_cpu_conf}}, threadpool, knobs, input_queue, output_queue, pipe);
  }
  output_queue->send_terminate_signal();

  auto ligand_out = output_queue->dequeue();
  if (!ligand_out) {
    mudock::error("The X-Score pipeline returned no ligand for ", ligand_path.string());
    return EXIT_FAILURE;
  }
  const auto score = ligand_out->properties.get(mudock::property_type::SCORE);

  bool ok = true;
  for (const auto term: term_names) {
    const auto expected = reference_value(reference_text, term);
    const auto actual   = scored_value(score, term);

    if (!expected.has_value()) {
      mudock::error("Reference ", ref_path.string(), " has no XSCORE_", std::string{term}, " entry");
      ok = false;
      continue;
    }
    if (!actual.has_value()) {
      mudock::error("muDock did not report a ",
                    std::string{term},
                    "= term; its score output was \"",
                    score,
                    "\"");
      ok = false;
      continue;
    }

    const auto delta = std::fabs(*actual - *expected);
    const auto limit = tolerance_for(*expected);
    if (delta <= limit)
      continue;

    mudock::error(std::format("{} mismatch for {}: mudock {:.6f} vs xscore {:.6f} (delta {:.3e}, "
                              "tolerance {:.3e})",
                              std::string{term},
                              ligand_path.filename().string(),
                              static_cast<double>(*actual),
                              static_cast<double>(*expected),
                              static_cast<double>(delta),
                              static_cast<double>(limit)));
    ok = false;
  }

  if (!ok) {
    mudock::error("X-Score verification FAILED for ", ligand_path.string());
    return EXIT_FAILURE;
  }

  mudock::info("Successfully verified the X-Score terms of ",
               ligand_path.filename().string(),
               " against ",
               ref_path.filename().string());
  return EXIT_SUCCESS;
}