#!/usr/bin/env bash

# Generates the X-Score reference values that `test_score_x` (ctest) checks muDock against.
#
# It needs the original XScore v1.3 build.
#
# For every <dir>/<name>/ holding <name>_protein.pdb and <name>_ligand.mol2 it runs XScore and writes
# <dir>/<name>/<name>_xscore.ref containing the four implemented terms plus the HPScore affinity.
#
# Usage:
#   ./script/gen_xscore_reference.sh                 # regenerate data/ and data_xscore/
#   ./script/gen_xscore_reference.sh data_xscore     # a single directory

set -u

export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --- xscore location ---
XSCORE="${XSCORE:-$HOME/xscore-dev/xscore_v1.3/c++/xscore}"
export XSCORE_PARAMETER="${XSCORE_PARAMETER:-$HOME/xscore-dev/xscore_v1.3/parameter/}"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

[ -x "$XSCORE" ] || { echo "xscore binary not found at $XSCORE" >&2; exit 1; }
[ -d "$XSCORE_PARAMETER" ] || { echo "XSCORE_PARAMETER not found at $XSCORE_PARAMETER" >&2; exit 1; }

if [ "$#" -gt 0 ]; then
  DIRS=("$@")
else
  DIRS=("$ROOT/data" "$ROOT/data_xscore")
fi

run_xscore() {
  local name="$1" pdb="$2" lig="$3" inp="$TMP/$1.input"
  cat > "$inp" <<EOF
FUNCTION            SCORE
RECEPTOR_PDB_FILE   $pdb
LIGAND_MOL2_FILE    $lig
OUTPUT_TABLE_FILE   $TMP/${name}.table
OUTPUT_LOG_FILE     $TMP/${name}.log
NUMBER_OF_HITS      1
HITS_DIRECTORY      $TMP/${name}.mdb
SHOW_ATOM_BIND_SCORE    NO
APPLY_HPSCORE       YES
APPLY_HMSCORE       YES
APPLY_HSSCORE       YES
APPLY_CHEMICAL_RULES    NO
EOF
  "$XSCORE" "$inp" 2>&1
}

written=0
skipped=0
failed=0

for dir in "${DIRS[@]}"; do
  [ -d "$dir" ] || { echo "skip: no such directory $dir"; continue; }
  for sub in "$dir"/*/; do
    [ -d "$sub" ] || continue
    name="$(basename "$sub")"
    pdb="$sub${name}_protein.pdb"
    lig="$sub${name}_ligand.mol2"
    if [ ! -f "$pdb" ] || [ ! -f "$lig" ]; then
      echo "skip $name (missing protein or ligand)"
      skipped=$((skipped + 1))
      continue
    fi

    out="$(run_xscore "$name" "$pdb" "$lig")"

    vdw="$(printf '%s\n' "$out" | grep -oE 'VDW=[^ ]+' | head -1 | cut -d= -f2)"
    hb="$( printf '%s\n' "$out" | grep -oE 'HB=[^ ]+'  | head -1 | cut -d= -f2)"
    hp="$( printf '%s\n' "$out" | grep -oE 'HP=[^ ]+'  | head -1 | cut -d= -f2)"
    rt="$( printf '%s\n' "$out" | grep -oE 'RT=[^ ]+'  | head -1 | cut -d= -f2)"
    pkd="$(printf '%s\n' "$out" | grep -oE 'PKD=[^ ]+' | head -1 | cut -d= -f2)"

    if [ -z "$vdw" ] || [ -z "$hb" ] || [ -z "$hp" ] || [ -z "$rt" ] || [ -z "$pkd" ]; then
      echo "FAIL  $name (xscore did not emit all five values -- left any existing .ref untouched)"
      failed=$((failed + 1))
      continue
    fi

    ref="$sub${name}_xscore.ref"
    cat > "$ref" <<EOF
# X-Score v1.3 reference values for $name -- HPScore terms.
# Generated by script/gen_xscore_reference.sh on $(date +%Y-%m-%d); do not edit by hand.
#
# PKD is XScore's pkd1 (HPScore): of the three -log(Kd) predictions XScore reports, the only one
# whose regression uses exactly the four terms muDock implements:
#     pKd = 3.441 + 0.004*VDW + 0.054*HB + 0.009*HP - 0.061*RT
# HMScore and HSScore need the HM / HS terms, which muDock does not compute.
XSCORE_VDW  $vdw
XSCORE_HB   $hb
XSCORE_HP   $hp
XSCORE_RT   $rt
XSCORE_PKD  $pkd
EOF
    echo "wrote $ref  (VDW=$vdw HB=$hb HP=$hp RT=$rt PKD=$pkd)"
    written=$((written + 1))
  done
done

echo
echo "=== SUMMARY ==="
echo "references written : $written"
echo "skipped            : $skipped"
echo "failed             : $failed"

[ "$failed" -eq 0 ]