#include <algorithm>
#include <mudock/chem/autodock_babel_types.hpp>

//===------------------------------------------------------------------------------------------------------
// WARNING: This file has been automatically generated from chem/autodock_babel_types.json
//===------------------------------------------------------------------------------------------------------

namespace mudock {
  const std::array<autodock_babel_ff_description, 145> AUTODOCK_BABEL_FF_DICTIONARY = {{
      {autodock_babel_ff::H, "H", element::H},         {autodock_babel_ff::HC, "HC", element::H},
      {autodock_babel_ff::He, "He", element::He},      {autodock_babel_ff::Li, "Li", element::Li},
      {autodock_babel_ff::Be, "Be", element::Be},      {autodock_babel_ff::B, "B", element::B},
      {autodock_babel_ff::C, "C", element::C},         {autodock_babel_ff::C1, "C1", element::C},
      {autodock_babel_ff::C2, "C2", element::C},       {autodock_babel_ff::C3, "C3", element::C},
      {autodock_babel_ff::Cac, "Cac", element::C},     {autodock_babel_ff::C_plus, "C+", element::C},
      {autodock_babel_ff::N, "N", element::N},         {autodock_babel_ff::Nox, "Nox", element::N},
      {autodock_babel_ff::N1, "N1", element::N},       {autodock_babel_ff::N2, "N2", element::N},
      {autodock_babel_ff::N3, "N3", element::N},       {autodock_babel_ff::N3_plus, "N3+", element::N},
      {autodock_babel_ff::Ntr, "Ntr", element::N},     {autodock_babel_ff::Npl, "Npl", element::N},
      {autodock_babel_ff::Ng_plus, "Ng+", element::N}, {autodock_babel_ff::Nam, "Nam", element::N},
      {autodock_babel_ff::O, "O", element::O},         {autodock_babel_ff::O_minus, "O-", element::O},
      {autodock_babel_ff::O3, "O3", element::O},       {autodock_babel_ff::O2, "O2", element::O},
      {autodock_babel_ff::F, "F", element::F},         {autodock_babel_ff::Ne, "Ne", element::Ne},
      {autodock_babel_ff::Na, "Na", element::Na},      {autodock_babel_ff::Mg, "Mg", element::Mg},
      {autodock_babel_ff::Al, "Al", element::Al},      {autodock_babel_ff::Si, "Si", element::Si},
      {autodock_babel_ff::P, "P", element::P},         {autodock_babel_ff::Pac, "Pac", element::P},
      {autodock_babel_ff::Pox, "Pox", element::P},     {autodock_babel_ff::P3_plus, "P3+", element::P},
      {autodock_babel_ff::S, "S", element::S},         {autodock_babel_ff::S2, "S2", element::S},
      {autodock_babel_ff::S3, "S3", element::S},       {autodock_babel_ff::S3_plus, "S3+", element::S},
      {autodock_babel_ff::Sac, "Sac", element::S},     {autodock_babel_ff::Sox, "Sox", element::S},
      {autodock_babel_ff::Cl, "Cl", element::Cl},      {autodock_babel_ff::Ar, "Ar", element::Ar},
      {autodock_babel_ff::K, "K", element::K},         {autodock_babel_ff::Ca, "Ca", element::Ca},
      {autodock_babel_ff::Sc, "Sc", element::Sc},      {autodock_babel_ff::Ti, "Ti", element::Ti},
      {autodock_babel_ff::V, "V", element::V},         {autodock_babel_ff::Cr, "Cr", element::Cr},
      {autodock_babel_ff::Mn, "Mn", element::Mn},      {autodock_babel_ff::Fe, "Fe", element::Fe},
      {autodock_babel_ff::Co, "Co", element::Co},      {autodock_babel_ff::Ni, "Ni", element::Ni},
      {autodock_babel_ff::Cu, "Cu", element::Cu},      {autodock_babel_ff::Zn, "Zn", element::Zn},
      {autodock_babel_ff::Ga, "Ga", element::Ga},      {autodock_babel_ff::Ge, "Ge", element::Ge},
      {autodock_babel_ff::As, "As", element::As},      {autodock_babel_ff::Se, "Se", element::Se},
      {autodock_babel_ff::Br, "Br", element::Br},      {autodock_babel_ff::Kr, "Kr", element::Kr},
      {autodock_babel_ff::Rb, "Rb", element::Rb},      {autodock_babel_ff::Sr, "Sr", element::Sr},
      {autodock_babel_ff::Y, "Y", element::Y},         {autodock_babel_ff::Zr, "Zr", element::Zr},
      {autodock_babel_ff::Nb, "Nb", element::Nb},      {autodock_babel_ff::Mo, "Mo", element::Mo},
      {autodock_babel_ff::Tc, "Tc", element::Tc},      {autodock_babel_ff::Ru, "Ru", element::Ru},
      {autodock_babel_ff::Rh, "Rh", element::Rh},      {autodock_babel_ff::Pd, "Pd", element::Pd},
      {autodock_babel_ff::Ag, "Ag", element::Ag},      {autodock_babel_ff::Cd, "Cd", element::Cd},
      {autodock_babel_ff::In, "In", element::In},      {autodock_babel_ff::Sn, "Sn", element::Sn},
      {autodock_babel_ff::Sb, "Sb", element::Sb},      {autodock_babel_ff::Te, "Te", element::Te},
      {autodock_babel_ff::I, "I", element::I},         {autodock_babel_ff::Xe, "Xe", element::Xe},
      {autodock_babel_ff::Cs, "Cs", element::Cs},      {autodock_babel_ff::Ba, "Ba", element::Ba},
      {autodock_babel_ff::La, "La", element::La},      {autodock_babel_ff::Ce, "Ce", element::Ce},
      {autodock_babel_ff::Pr, "Pr", element::Pr},      {autodock_babel_ff::Nd, "Nd", element::Nd},
      {autodock_babel_ff::Pm, "Pm", element::Pm},      {autodock_babel_ff::Sm, "Sm", element::Sm},
      {autodock_babel_ff::Eu, "Eu", element::Eu},      {autodock_babel_ff::Gd, "Gd", element::Gd},
      {autodock_babel_ff::Tb, "Tb", element::Tb},      {autodock_babel_ff::Dy, "Dy", element::Dy},
      {autodock_babel_ff::Ho, "Ho", element::Ho},      {autodock_babel_ff::Er, "Er", element::Er},
      {autodock_babel_ff::Tm, "Tm", element::Tm},      {autodock_babel_ff::Yb, "Yb", element::Yb},
      {autodock_babel_ff::Lu, "Lu", element::Lu},      {autodock_babel_ff::Hf, "Hf", element::Hf},
      {autodock_babel_ff::Ta, "Ta", element::Ta},      {autodock_babel_ff::W, "W", element::W},
      {autodock_babel_ff::Re, "Re", element::Re},      {autodock_babel_ff::Os, "Os", element::Os},
      {autodock_babel_ff::Ir, "Ir", element::Ir},      {autodock_babel_ff::Pt, "Pt", element::Pt},
      {autodock_babel_ff::Au, "Au", element::Au},      {autodock_babel_ff::Hg, "Hg", element::Hg},
      {autodock_babel_ff::Tl, "Tl", element::Tl},      {autodock_babel_ff::Pb, "Pb", element::Pb},
      {autodock_babel_ff::Bi, "Bi", element::Bi},      {autodock_babel_ff::Po, "Po", element::Po},
      {autodock_babel_ff::At, "At", element::At},      {autodock_babel_ff::Rn, "Rn", element::Rn},
      {autodock_babel_ff::Fr, "Fr", element::Fr},      {autodock_babel_ff::Ra, "Ra", element::Ra},
      {autodock_babel_ff::Ac, "Ac", element::Ac},      {autodock_babel_ff::Th, "Th", element::Th},
      {autodock_babel_ff::Pa, "Pa", element::Pa},      {autodock_babel_ff::U, "U", element::U},
      {autodock_babel_ff::Np, "Np", element::Np},      {autodock_babel_ff::Pu, "Pu", element::Pu},
      {autodock_babel_ff::Am, "Am", element::Am},      {autodock_babel_ff::Cm, "Cm", element::Cm},
      {autodock_babel_ff::Bk, "Bk", element::Bk},      {autodock_babel_ff::Cf, "Cf", element::Cf},
      {autodock_babel_ff::Es, "Es", element::Es},      {autodock_babel_ff::Fm, "Fm", element::Fm},
      {autodock_babel_ff::Md, "Md", element::Md},      {autodock_babel_ff::No, "No", element::No},
      {autodock_babel_ff::Lr, "Lr", element::Lr},      {autodock_babel_ff::Rf, "Rf", element::Rf},
      {autodock_babel_ff::Db, "Db", element::Db},      {autodock_babel_ff::Sg, "Sg", element::Sg},
      {autodock_babel_ff::Bh, "Bh", element::Bh},      {autodock_babel_ff::Hs, "Hs", element::Hs},
      {autodock_babel_ff::Mt, "Mt", element::Mt},      {autodock_babel_ff::Ds, "Ds", element::Ds},
      {autodock_babel_ff::Rg, "Rg", element::Rg},      {autodock_babel_ff::Cn, "Cn", element::Cn},
      {autodock_babel_ff::Nh, "Nh", element::Nh},      {autodock_babel_ff::Fl, "Fl", element::Fl},
      {autodock_babel_ff::Mc, "Mc", element::Mc},      {autodock_babel_ff::Lv, "Lv", element::Lv},
      {autodock_babel_ff::Ts, "Ts", element::Ts},      {autodock_babel_ff::Og, "Og", element::Og},
      {autodock_babel_ff::Uue, "Uue", element::Uue},
  }};

} // namespace mudock
