#include <algorithm>
#include <mudock/chem/elements.hpp>

//===------------------------------------------------------------------------------------------------------
// WARNING: This file has been automatically generated from chem/periodic_table.json
//===------------------------------------------------------------------------------------------------------

namespace mudock {

  std::optional<element> parse_element_symbol(const std::string_view symbol) {
    const auto element_it = std::find_if(std::begin(ELEMENT_DICTIONARY),
                                         std::end(ELEMENT_DICTIONARY),
                                         [&symbol](const auto& e) { return e.symbol == symbol; });
    return element_it != std::end(ELEMENT_DICTIONARY) ? std::optional{element_it->value}
                                                      : std::optional<element>{};
  }

  const std::array<element_description, 119> ELEMENT_DICTIONARY = {{
      {element::H, "H", "Hydrogen", 1, 0},
      {element::He, "He", "Helium", 2, 0},
      {element::Li, "Li", "Lithium", 3, 1},
      {element::Be, "Be", "Beryllium", 4, 2},
      {element::B, "B", "Boron", 5, 3},
      {element::C, "C", "Carbon", 6, 4},
      {element::N, "N", "Nitrogen", 7, 5},
      {element::O, "O", "Oxygen", 8, 6},
      {element::F, "F", "Fluorine", 9, 7},
      {element::Ne, "Ne", "Neon", 10, 8},
      {element::Na, "Na", "Sodium", 11, 1},
      {element::Mg, "Mg", "Magnesium", 12, 2},
      {element::Al, "Al", "Aluminium", 13, 3},
      {element::Si, "Si", "Silicon", 14, 4},
      {element::P, "P", "Phosphorus", 15, 5},
      {element::S, "S", "Sulfur", 16, 6},
      {element::Cl, "Cl", "Chlorine", 17, 7},
      {element::Ar, "Ar", "Argon", 18, 8},
      {element::K, "K", "Potassium", 19, 1},
      {element::Ca, "Ca", "Calcium", 20, 2},
      {element::Sc, "Sc", "Scandium", 21, 3},
      {element::Ti, "Ti", "Titanium", 22, 4},
      {element::V, "V", "Vanadium", 23, 5},
      {element::Cr, "Cr", "Chromium", 24, 6},
      {element::Mn, "Mn", "Manganese", 25, 7},
      {element::Fe, "Fe", "Iron", 26, 8},
      {element::Co, "Co", "Cobalt", 27, 9},
      {element::Ni, "Ni", "Nickel", 28, 10},
      {element::Cu, "Cu", "Copper", 29, 11},
      {element::Zn, "Zn", "Zinc", 30, 12},
      {element::Ga, "Ga", "Gallium", 31, 13},
      {element::Ge, "Ge", "Germanium", 32, 14},
      {element::As, "As", "Arsenic", 33, 15},
      {element::Se, "Se", "Selenium", 34, 16},
      {element::Br, "Br", "Bromine", 35, 17},
      {element::Kr, "Kr", "Krypton", 36, 18},
      {element::Rb, "Rb", "Rubidium", 37, 1},
      {element::Sr, "Sr", "Strontium", 38, 2},
      {element::Y, "Y", "Yttrium", 39, 3},
      {element::Zr, "Zr", "Zirconium", 40, 4},
      {element::Nb, "Nb", "Niobium", 41, 5},
      {element::Mo, "Mo", "Molybdenum", 42, 6},
      {element::Tc, "Tc", "Technetium", 43, 7},
      {element::Ru, "Ru", "Ruthenium", 44, 8},
      {element::Rh, "Rh", "Rhodium", 45, 9},
      {element::Pd, "Pd", "Palladium", 46, 10},
      {element::Ag, "Ag", "Silver", 47, 11},
      {element::Cd, "Cd", "Cadmium", 48, 12},
      {element::In, "In", "Indium", 49, 13},
      {element::Sn, "Sn", "Tin", 50, 14},
      {element::Sb, "Sb", "Antimony", 51, 15},
      {element::Te, "Te", "Tellurium", 52, 16},
      {element::I, "I", "Iodine", 53, 17},
      {element::Xe, "Xe", "Xenon", 54, 18},
      {element::Cs, "Cs", "Cesium", 55, 1},
      {element::Ba, "Ba", "Barium", 56, 2},
      {element::La, "La", "Lanthanum", 57, 3},
      {element::Ce, "Ce", "Cerium", 58, 4},
      {element::Pr, "Pr", "Praseodymium", 59, 5},
      {element::Nd, "Nd", "Neodymium", 60, 6},
      {element::Pm, "Pm", "Promethium", 61, 7},
      {element::Sm, "Sm", "Samarium", 62, 8},
      {element::Eu, "Eu", "Europium", 63, 9},
      {element::Gd, "Gd", "Gadolinium", 64, 10},
      {element::Tb, "Tb", "Terbium", 65, 11},
      {element::Dy, "Dy", "Dysprosium", 66, 12},
      {element::Ho, "Ho", "Holmium", 67, 13},
      {element::Er, "Er", "Erbium", 68, 14},
      {element::Tm, "Tm", "Thulium", 69, 15},
      {element::Yb, "Yb", "Ytterbium", 70, 16},
      {element::Lu, "Lu", "Lutetium", 71, 17},
      {element::Hf, "Hf", "Hafnium", 72, 18},
      {element::Ta, "Ta", "Tantalum", 73, 19},
      {element::W, "W", "Tungsten", 74, 20},
      {element::Re, "Re", "Rhenium", 75, 21},
      {element::Os, "Os", "Osmium", 76, 22},
      {element::Ir, "Ir", "Iridium", 77, 23},
      {element::Pt, "Pt", "Platinum", 78, 24},
      {element::Au, "Au", "Gold", 79, 25},
      {element::Hg, "Hg", "Mercury", 80, 26},
      {element::Tl, "Tl", "Thallium", 81, 27},
      {element::Pb, "Pb", "Lead", 82, 28},
      {element::Bi, "Bi", "Bismuth", 83, 29},
      {element::Po, "Po", "Polonium", 84, 30},
      {element::At, "At", "Astatine", 85, 31},
      {element::Rn, "Rn", "Radon", 86, 32},
      {element::Fr, "Fr", "Francium", 87, 1},
      {element::Ra, "Ra", "Radium", 88, 2},
      {element::Ac, "Ac", "Actinium", 89, 3},
      {element::Th, "Th", "Thorium", 90, 4},
      {element::Pa, "Pa", "Protactinium", 91, 5},
      {element::U, "U", "Uranium", 92, 6},
      {element::Np, "Np", "Neptunium", 93, 7},
      {element::Pu, "Pu", "Plutonium", 94, 8},
      {element::Am, "Am", "Americium", 95, 9},
      {element::Cm, "Cm", "Curium", 96, 10},
      {element::Bk, "Bk", "Berkelium", 97, 11},
      {element::Cf, "Cf", "Californium", 98, 12},
      {element::Es, "Es", "Einsteinium", 99, 13},
      {element::Fm, "Fm", "Fermium", 100, 14},
      {element::Md, "Md", "Mendelevium", 101, 15},
      {element::No, "No", "Nobelium", 102, 16},
      {element::Lr, "Lr", "Lawrencium", 103, 17},
      {element::Rf, "Rf", "Rutherfordium", 104, 18},
      {element::Db, "Db", "Dubnium", 105, 19},
      {element::Sg, "Sg", "Seaborgium", 106, 20},
      {element::Bh, "Bh", "Bohrium", 107, 21},
      {element::Hs, "Hs", "Hassium", 108, 22},
      {element::Mt, "Mt", "Meitnerium", 109, 23},
      {element::Ds, "Ds", "Darmstadtium", 110, 24},
      {element::Rg, "Rg", "Roentgenium", 111, 25},
      {element::Cn, "Cn", "Copernicium", 112, 26},
      {element::Nh, "Nh", "Nihonium", 113, 27},
      {element::Fl, "Fl", "Flerovium", 114, 28},
      {element::Mc, "Mc", "Moscovium", 115, 29},
      {element::Lv, "Lv", "Livermorium", 116, 30},
      {element::Ts, "Ts", "Tennessine", 117, 31},
      {element::Og, "Og", "Oganesson", 118, 32},
      {element::Uue, "Uue", "Ununennium", 119, 1},
  }};

} // namespace mudock
